input_dir: "/Users/puravgupta/Documents/Research/Pancreas_TLS_ML/WSI/"
results_dir: "/Users/puravgupta/Documents/Research/Pancreas_TLS_ML/2025-HistoPath-TLS-Purav/art_out/"
grandqc_path: "/Users/puravgupta/Documents/Research/Pancreas_TLS_ML/grandqc/01_WSI_inference_OPENSLIDE_QC"
