input_dir: "/ddn_exa/campbell/share/datasets/TCGA-histopath/"
results_dir: "/ddn_exa/campbell/pgupta/2025-HistoPath-TLS-Purav/TCGA_out/"
grandqc_path: "/ddn_exa/campbell/pgupta/grandqc/01_WSI_inference_OPENSLIDE_QC/"
