results_dir: "/ddn_exa/campbell/pgupta/2025-HistoPath-TLS-Purav/TLS_gallery"
input_dir: "/ddn_exa/campbell/pgupta/TCGA_data"
tls_geojson_dir: "tls_geojson"
qc_geojson_dir: "qc_geojson"
wsi_level: 0  # WSI level for visualization (0 is highest resolution)